# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 20:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_text', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Canine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_text', models.CharField(max_length=50, unique=True)),
                ('direction_short', models.CharField(max_length=2)),
                ('direction_deg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_range', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey_Elevation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=20, unique=True)),
                ('staff_type', models.CharField(max_length=50)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('hawaiian_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RandomPoints',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True, null=True)),
                ('near', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('from_0_to_10', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_10_to_20', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_20_to_30', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_30_to_40', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_40_to_50', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_50_to_60', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_60_to_70', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('from_70_to_80', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('total_searchable', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('locations', models.CharField(max_length=200, unique=True)),
                ('short', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('species_code', models.CharField(max_length=10)),
                ('species_status', models.CharField(choices=[(b'MBTA', b'MBTA'), (b'Endangered', b'Endangerd'), (b'Non-listed', b'Non-listed'), (b'Game', b'Game')], max_length=50)),
                ('size_class', models.CharField(choices=[(b'Small', b'Small'), (b'Medium', b'Medium'), (b'Large', b'Large')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trap_type_text', models.CharField(max_length=200, unique=True)),
                ('cost', models.CharField(max_length=200)),
                ('check_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='searcharea',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site'),
        ),
        migrations.AddField(
            model_name='searcharea',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Infrastructure'),
        ),
        migrations.AddField(
            model_name='randompoints',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_tables.Site'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='lookup_tables.Site'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='physical_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_location', to='lookup_tables.Site'),
        ),
    ]
