# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NightSurvey_Behavior',
        ),
        migrations.DeleteModel(
            name='NightSurvey_Distance',
        ),
        migrations.DeleteModel(
            name='NightSurvey_Elevation',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
