# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0003_delete_bandcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='randompoints',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='randompoints',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
