# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0004_auto_20170604_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bait',
        ),
    ]
