# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0006_auto_20170608_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='species_code',
            field=models.CharField(default='', help_text=b'first three letters of genus and species', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
