# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0007_plantspecies_species_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecies',
            name='distribution',
            field=models.CharField(choices=[(b'Endemic', b'Endemic'), (b'Indigenous', b'Indigenous'), (b'Naturalized', b'Naturalized')], max_length=200),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='status',
            field=models.CharField(choices=[(b'Non-listed', b'Non-listed'), (b'Threatened', b'Threatened'), (b'Endangered', b'Endangered')], max_length=200),
        ),
        migrations.AlterField(
            model_name='speciesdef',
            name='species_code',
            field=models.CharField(help_text=b"<a href='http://www.birdpop.org/docs/misc/Alpha_codes_tax.pdf' target='_blank'>4 letter code</a> ", max_length=10, unique=True),
        ),
    ]
